default_mysql: &default_mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default_mysql
  database: hm_dev
  username: root
  password: ""

test:
  <<: *default_mysql
  database: hm_test
  username: root

production:
  <<: *default_mysql
  database: hm_pro
  username: root
  password: 
